query GetInstance {
  serviceInstance(environmentId: "c0c46f85-22c8-4f67-8ed6-79e1a2d70c54", serviceId: "fe36624a-15a4-4f72-ad51-251bfdc222b7") {
    id
    rootDirectory
    builder
    dockerfilePath
    buildCommand
    startCommand
    serviceName
    upstreamUrl
  }
}
