mutation {
  serviceInstanceUpdate(
    serviceId: "80ece875-eadd-4ba6-bab5-79cf7ba7c4ca",
    environmentId: "c0c46f85-22c8-4f67-8ed6-79e1a2d70c54",
    input: {
      rootDirectory: "apps/web"
    }
  )
}
